apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-seed-job
  # <YOUR_NAMESPACE>: change to the current namespace
  namespace: danielrei-dev
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seeder
          # <YOUR_NAMESPACE>: change to the current namespace
          # <YOUR_DEPLOYMENT>: change to the current deployment
          image: image-registry.openshift-image-registry.svc:5000/<YOUR_NAMESPACE>/<YOUR_DEPLOYMENT>:latest
          command: ["node", "src/scripts/seed.js", "--idempotent"]
          envFrom:
            - configMapRef:
                name: backend-config-prod
            - secretRef:
                name: backend-secrets-prod
